### ISSUE TITLE
error into example project "duecan_bootloader"

### ISSUE THREAD

**Issue by biccius** [collin80/FirmwareReceiver#2]
Hi

I think there is a wrong number of parameters into the example project "duecan_bootloader" when the write method of the class "DueFlashStorage" is called

`dueFlashStorage.write(flashWritePosition, pageBuffer, IFLASH1_PAGE_SIZE, 0);`

Declarations are the following:

	boolean write(uint32_t address, byte value);
	boolean write(uint32_t address, byte *data, uint32_t dataLength);

I think that the last parameter "0" is useless

**Comment by collin80** [comment]
Well, yes, that might be true of the version of DueFlashStorage you've got.
But, if you use the old version found in my repos then the syntax I'm using
is correct. As you can see from the repo, I haven't updated the library in
three years. I haven't really done much with the firmwarereceiver stuff in
about that long too. It doesn't look too complicated to fix up the code to
work with a newer version of DueFlashStorage but I don't know if/when I
might ever get around to doing that myself. I don't use this library for
much of anything any longer.

**Comment by biccius** [comment]
Sorry, i didn't checked the version in your repository but i had taken the latest version of the official library

`
boolean write(uint32_t address, byte *data, uint32_t dataLength, int block);`

Thank you
